// AUTO-GENERATED from the backend canonical concelho polygon set
// (fogosapi-dotnet ConcelhoPolygons.geojson — 278 mainland concelhos). Do not edit by hand.
// No GraphQL locations/concelhos query exists and incidents carry only concelho names,
// so the alert concelho picker resolves a DICO from this static list.

export interface ConcelhoEntry {
  /** Zero-padded 4-char DICO code. */
  dico: string
  name: string
  district: string
}

export const CONCELHOS: ConcelhoEntry[] = [
  { dico: "1401", name: "Abrantes", district: "Santarém" },
  { dico: "0101", name: "Águeda", district: "Aveiro" },
  { dico: "0901", name: "Aguiar da Beira", district: "Guarda" },
  { dico: "0701", name: "Alandroal", district: "Évora" },
  { dico: "0102", name: "Albergaria-A-Velha", district: "Aveiro" },
  { dico: "0801", name: "Albufeira", district: "Faro" },
  { dico: "1501", name: "Alcácer do Sal", district: "Setúbal" },
  { dico: "1402", name: "Alcanena", district: "Santarém" },
  { dico: "1001", name: "Alcobaça", district: "Leiria" },
  { dico: "1502", name: "Alcochete", district: "Setúbal" },
  { dico: "0802", name: "Alcoutim", district: "Faro" },
  { dico: "1101", name: "Alenquer", district: "Lisboa" },
  { dico: "0401", name: "Alfândega da Fé", district: "Bragança" },
  { dico: "1701", name: "Alijó", district: "Vila Real" },
  { dico: "0803", name: "Aljezur", district: "Faro" },
  { dico: "0201", name: "Aljustrel", district: "Beja" },
  { dico: "1503", name: "Almada", district: "Setúbal" },
  { dico: "0902", name: "Almeida", district: "Guarda" },
  { dico: "1403", name: "Almeirim", district: "Santarém" },
  { dico: "0202", name: "Almodôvar", district: "Beja" },
  { dico: "1404", name: "Alpiarça", district: "Santarém" },
  { dico: "1201", name: "Alter do Chão", district: "Portalegre" },
  { dico: "1002", name: "Alvaiázere", district: "Leiria" },
  { dico: "0203", name: "Alvito", district: "Beja" },
  { dico: "1115", name: "Amadora", district: "Lisboa" },
  { dico: "1301", name: "Amarante", district: "Porto" },
  { dico: "0301", name: "Amares", district: "Braga" },
  { dico: "0103", name: "Anadia", district: "Aveiro" },
  { dico: "1003", name: "Ansião", district: "Leiria" },
  { dico: "1601", name: "Arcos de Valdevez", district: "Viana do Castelo" },
  { dico: "0601", name: "Arganil", district: "Coimbra" },
  { dico: "1801", name: "Armamar", district: "Viseu" },
  { dico: "0104", name: "Arouca", district: "Aveiro" },
  { dico: "0702", name: "Arraiolos", district: "Évora" },
  { dico: "1202", name: "Arronches", district: "Portalegre" },
  { dico: "1102", name: "Arruda dos Vinhos", district: "Lisboa" },
  { dico: "0105", name: "Aveiro", district: "Aveiro" },
  { dico: "1203", name: "Avis", district: "Portalegre" },
  { dico: "1103", name: "Azambuja", district: "Lisboa" },
  { dico: "1302", name: "Baião", district: "Porto" },
  { dico: "0302", name: "Barcelos", district: "Braga" },
  { dico: "0204", name: "Barrancos", district: "Beja" },
  { dico: "1504", name: "Barreiro", district: "Setúbal" },
  { dico: "1004", name: "Batalha", district: "Leiria" },
  { dico: "0205", name: "Beja", district: "Beja" },
  { dico: "0501", name: "Belmonte", district: "Castelo Branco" },
  { dico: "1405", name: "Benavente", district: "Santarém" },
  { dico: "1005", name: "Bombarral", district: "Leiria" },
  { dico: "0703", name: "Borba", district: "Évora" },
  { dico: "1702", name: "Boticas", district: "Vila Real" },
  { dico: "0303", name: "Braga", district: "Braga" },
  { dico: "0402", name: "Bragança", district: "Bragança" },
  { dico: "0304", name: "Cabeceiras de Basto", district: "Braga" },
  { dico: "1104", name: "Cadaval", district: "Lisboa" },
  { dico: "1006", name: "Caldas da Rainha", district: "Leiria" },
  { dico: "1602", name: "Caminha", district: "Viana do Castelo" },
  { dico: "1204", name: "Campo Maior", district: "Portalegre" },
  { dico: "0602", name: "Cantanhede", district: "Coimbra" },
  { dico: "0403", name: "Carrazeda de Ansiães", district: "Bragança" },
  { dico: "1802", name: "Carregal do Sal", district: "Viseu" },
  { dico: "1406", name: "Cartaxo", district: "Santarém" },
  { dico: "1105", name: "Cascais", district: "Lisboa" },
  { dico: "1007", name: "Castanheira de Pêra", district: "Leiria" },
  { dico: "0502", name: "Castelo Branco", district: "Castelo Branco" },
  { dico: "0106", name: "Castelo de Paiva", district: "Aveiro" },
  { dico: "1205", name: "Castelo de Vide", district: "Portalegre" },
  { dico: "1803", name: "Castro Daire", district: "Viseu" },
  { dico: "0804", name: "Castro Marim", district: "Faro" },
  { dico: "0206", name: "Castro Verde", district: "Beja" },
  { dico: "0903", name: "Celorico da Beira", district: "Guarda" },
  { dico: "0305", name: "Celorico de Basto", district: "Braga" },
  { dico: "1407", name: "Chamusca", district: "Santarém" },
  { dico: "1703", name: "Chaves", district: "Vila Real" },
  { dico: "1804", name: "Cinfães", district: "Viseu" },
  { dico: "0603", name: "Coimbra", district: "Coimbra" },
  { dico: "0604", name: "Condeixa-A-Nova", district: "Coimbra" },
  { dico: "1408", name: "Constância", district: "Santarém" },
  { dico: "1409", name: "Coruche", district: "Santarém" },
  { dico: "0503", name: "Covilhã", district: "Castelo Branco" },
  { dico: "1206", name: "Crato", district: "Portalegre" },
  { dico: "0207", name: "Cuba", district: "Beja" },
  { dico: "1207", name: "Elvas", district: "Portalegre" },
  { dico: "1410", name: "Entroncamento", district: "Santarém" },
  { dico: "0107", name: "Espinho", district: "Aveiro" },
  { dico: "0306", name: "Esposende", district: "Braga" },
  { dico: "0108", name: "Estarreja", district: "Aveiro" },
  { dico: "0704", name: "Estremoz", district: "Évora" },
  { dico: "0705", name: "Évora", district: "Évora" },
  { dico: "0307", name: "Fafe", district: "Braga" },
  { dico: "0805", name: "Faro", district: "Faro" },
  { dico: "1303", name: "Felgueiras", district: "Porto" },
  { dico: "0208", name: "Ferreira do Alentejo", district: "Beja" },
  { dico: "1411", name: "Ferreira do Zêzere", district: "Santarém" },
  { dico: "0605", name: "Figueira da Foz", district: "Coimbra" },
  { dico: "0904", name: "Figueira de Castelo Rodrigo", district: "Guarda" },
  { dico: "1008", name: "Figueiró dos Vinhos", district: "Leiria" },
  { dico: "0905", name: "Fornos de Algodres", district: "Guarda" },
  { dico: "0404", name: "Freixo de Espada À Cinta", district: "Bragança" },
  { dico: "1208", name: "Fronteira", district: "Portalegre" },
  { dico: "0504", name: "Fundão", district: "Castelo Branco" },
  { dico: "1209", name: "Gavião", district: "Portalegre" },
  { dico: "0606", name: "Góis", district: "Coimbra" },
  { dico: "1412", name: "Golegã", district: "Santarém" },
  { dico: "1304", name: "Gondomar", district: "Porto" },
  { dico: "0906", name: "Gouveia", district: "Guarda" },
  { dico: "1505", name: "Grândola", district: "Setúbal" },
  { dico: "0907", name: "Guarda", district: "Guarda" },
  { dico: "0308", name: "Guimarães", district: "Braga" },
  { dico: "0505", name: "Idanha-A-Nova", district: "Castelo Branco" },
  { dico: "0110", name: "Ílhavo", district: "Aveiro" },
  { dico: "0806", name: "Lagoa", district: "Faro" },
  { dico: "0807", name: "Lagos", district: "Faro" },
  { dico: "1805", name: "Lamego", district: "Viseu" },
  { dico: "1009", name: "Leiria", district: "Leiria" },
  { dico: "1106", name: "Lisboa", district: "Lisboa" },
  { dico: "0808", name: "Loulé", district: "Faro" },
  { dico: "1107", name: "Loures", district: "Lisboa" },
  { dico: "1108", name: "Lourinhã", district: "Lisboa" },
  { dico: "0607", name: "Lousã", district: "Coimbra" },
  { dico: "1305", name: "Lousada", district: "Porto" },
  { dico: "1413", name: "Mação", district: "Santarém" },
  { dico: "0405", name: "Macedo de Cavaleiros", district: "Bragança" },
  { dico: "1109", name: "Mafra", district: "Lisboa" },
  { dico: "1306", name: "Maia", district: "Porto" },
  { dico: "1806", name: "Mangualde", district: "Viseu" },
  { dico: "0908", name: "Manteigas", district: "Guarda" },
  { dico: "1307", name: "Marco de Canaveses", district: "Porto" },
  { dico: "1010", name: "Marinha Grande", district: "Leiria" },
  { dico: "1210", name: "Marvão", district: "Portalegre" },
  { dico: "1308", name: "Matosinhos", district: "Porto" },
  { dico: "0111", name: "Mealhada", district: "Aveiro" },
  { dico: "0909", name: "Mêda", district: "Guarda" },
  { dico: "1603", name: "Melgaço", district: "Viana do Castelo" },
  { dico: "0209", name: "Mértola", district: "Beja" },
  { dico: "1704", name: "Mesão Frio", district: "Vila Real" },
  { dico: "0608", name: "Mira", district: "Coimbra" },
  { dico: "0609", name: "Miranda do Corvo", district: "Coimbra" },
  { dico: "0406", name: "Miranda do Douro", district: "Bragança" },
  { dico: "0407", name: "Mirandela", district: "Bragança" },
  { dico: "0408", name: "Mogadouro", district: "Bragança" },
  { dico: "1807", name: "Moimenta da Beira", district: "Viseu" },
  { dico: "1506", name: "Moita", district: "Setúbal" },
  { dico: "1604", name: "Monção", district: "Viana do Castelo" },
  { dico: "0809", name: "Monchique", district: "Faro" },
  { dico: "1705", name: "Mondim de Basto", district: "Vila Real" },
  { dico: "1211", name: "Monforte", district: "Portalegre" },
  { dico: "1706", name: "Montalegre", district: "Vila Real" },
  { dico: "0706", name: "Montemor-O-Novo", district: "Évora" },
  { dico: "0610", name: "Montemor-O-Velho", district: "Coimbra" },
  { dico: "1507", name: "Montijo", district: "Setúbal" },
  { dico: "0707", name: "Mora", district: "Évora" },
  { dico: "1808", name: "Mortágua", district: "Viseu" },
  { dico: "0210", name: "Moura", district: "Beja" },
  { dico: "0708", name: "Mourão", district: "Évora" },
  { dico: "1707", name: "Murça", district: "Vila Real" },
  { dico: "0112", name: "Murtosa", district: "Aveiro" },
  { dico: "1011", name: "Nazaré", district: "Leiria" },
  { dico: "1809", name: "Nelas", district: "Viseu" },
  { dico: "1212", name: "Nisa", district: "Portalegre" },
  { dico: "1012", name: "Óbidos", district: "Leiria" },
  { dico: "0211", name: "Odemira", district: "Beja" },
  { dico: "1116", name: "Odivelas", district: "Lisboa" },
  { dico: "1110", name: "Oeiras", district: "Lisboa" },
  { dico: "0506", name: "Oleiros", district: "Castelo Branco" },
  { dico: "0810", name: "Olhão", district: "Faro" },
  { dico: "0113", name: "Oliveira de Azeméis", district: "Aveiro" },
  { dico: "1810", name: "Oliveira de Frades", district: "Viseu" },
  { dico: "0114", name: "Oliveira do Bairro", district: "Aveiro" },
  { dico: "0611", name: "Oliveira do Hospital", district: "Coimbra" },
  { dico: "1421", name: "Ourém", district: "Santarém" },
  { dico: "0212", name: "Ourique", district: "Beja" },
  { dico: "0115", name: "Ovar", district: "Aveiro" },
  { dico: "1309", name: "Paços de Ferreira", district: "Porto" },
  { dico: "1508", name: "Palmela", district: "Setúbal" },
  { dico: "0612", name: "Pampilhosa da Serra", district: "Coimbra" },
  { dico: "1310", name: "Paredes", district: "Porto" },
  { dico: "1605", name: "Paredes de Coura", district: "Viana do Castelo" },
  { dico: "1013", name: "Pedrógão Grande", district: "Leiria" },
  { dico: "0613", name: "Penacova", district: "Coimbra" },
  { dico: "1311", name: "Penafiel", district: "Porto" },
  { dico: "1811", name: "Penalva do Castelo", district: "Viseu" },
  { dico: "0507", name: "Penamacor", district: "Castelo Branco" },
  { dico: "1812", name: "Penedono", district: "Viseu" },
  { dico: "0614", name: "Penela", district: "Coimbra" },
  { dico: "1014", name: "Peniche", district: "Leiria" },
  { dico: "1708", name: "Peso da Régua", district: "Vila Real" },
  { dico: "0910", name: "Pinhel", district: "Guarda" },
  { dico: "1015", name: "Pombal", district: "Leiria" },
  { dico: "1606", name: "Ponte da Barca", district: "Viana do Castelo" },
  { dico: "1607", name: "Ponte de Lima", district: "Viana do Castelo" },
  { dico: "1213", name: "Ponte de Sor", district: "Portalegre" },
  { dico: "1214", name: "Portalegre", district: "Portalegre" },
  { dico: "0709", name: "Portel", district: "Évora" },
  { dico: "0811", name: "Portimão", district: "Faro" },
  { dico: "1312", name: "Porto", district: "Porto" },
  { dico: "1016", name: "Porto de Mós", district: "Leiria" },
  { dico: "0309", name: "Póvoa de Lanhoso", district: "Braga" },
  { dico: "1313", name: "Póvoa de Varzim", district: "Porto" },
  { dico: "0508", name: "Proença-A-Nova", district: "Castelo Branco" },
  { dico: "0710", name: "Redondo", district: "Évora" },
  { dico: "0711", name: "Reguengos de Monsaraz", district: "Évora" },
  { dico: "1813", name: "Resende", district: "Viseu" },
  { dico: "1709", name: "Ribeira de Pena", district: "Vila Real" },
  { dico: "1414", name: "Rio Maior", district: "Santarém" },
  { dico: "1710", name: "Sabrosa", district: "Vila Real" },
  { dico: "0911", name: "Sabugal", district: "Guarda" },
  { dico: "1415", name: "Salvaterra de Magos", district: "Santarém" },
  { dico: "1814", name: "Santa Comba Dão", district: "Viseu" },
  { dico: "0109", name: "Santa Maria da Feira", district: "Aveiro" },
  { dico: "1711", name: "Santa Marta de Penaguião", district: "Vila Real" },
  { dico: "1416", name: "Santarém", district: "Santarém" },
  { dico: "1509", name: "Santiago do Cacém", district: "Setúbal" },
  { dico: "1314", name: "Santo Tirso", district: "Porto" },
  { dico: "0812", name: "São Brás de Alportel", district: "Faro" },
  { dico: "0116", name: "São João da Madeira", district: "Aveiro" },
  { dico: "1815", name: "São João da Pesqueira", district: "Viseu" },
  { dico: "1816", name: "São Pedro do Sul", district: "Viseu" },
  { dico: "1417", name: "Sardoal", district: "Santarém" },
  { dico: "1817", name: "Sátão", district: "Viseu" },
  { dico: "0912", name: "Seia", district: "Guarda" },
  { dico: "1510", name: "Seixal", district: "Setúbal" },
  { dico: "1818", name: "Sernancelhe", district: "Viseu" },
  { dico: "0213", name: "Serpa", district: "Beja" },
  { dico: "0509", name: "Sertã", district: "Castelo Branco" },
  { dico: "1511", name: "Sesimbra", district: "Setúbal" },
  { dico: "1512", name: "Setúbal", district: "Setúbal" },
  { dico: "0117", name: "Sever do Vouga", district: "Aveiro" },
  { dico: "0813", name: "Silves", district: "Faro" },
  { dico: "1513", name: "Sines", district: "Setúbal" },
  { dico: "1111", name: "Sintra", district: "Lisboa" },
  { dico: "1112", name: "Sobral de Monte Agraço", district: "Lisboa" },
  { dico: "0615", name: "Soure", district: "Coimbra" },
  { dico: "1215", name: "Sousel", district: "Portalegre" },
  { dico: "0616", name: "Tábua", district: "Coimbra" },
  { dico: "1819", name: "Tabuaço", district: "Viseu" },
  { dico: "1820", name: "Tarouca", district: "Viseu" },
  { dico: "0814", name: "Tavira", district: "Faro" },
  { dico: "0310", name: "Terras de Bouro", district: "Braga" },
  { dico: "1418", name: "Tomar", district: "Santarém" },
  { dico: "1821", name: "Tondela", district: "Viseu" },
  { dico: "0409", name: "Torre de Moncorvo", district: "Bragança" },
  { dico: "1419", name: "Torres Novas", district: "Santarém" },
  { dico: "1113", name: "Torres Vedras", district: "Lisboa" },
  { dico: "0913", name: "Trancoso", district: "Guarda" },
  { dico: "1318", name: "Trofa", district: "Porto" },
  { dico: "0118", name: "Vagos", district: "Aveiro" },
  { dico: "0119", name: "Vale de Cambra", district: "Aveiro" },
  { dico: "1608", name: "Valença", district: "Viana do Castelo" },
  { dico: "1315", name: "Valongo", district: "Porto" },
  { dico: "1712", name: "Valpaços", district: "Vila Real" },
  { dico: "0712", name: "Vendas Novas", district: "Évora" },
  { dico: "0713", name: "Viana do Alentejo", district: "Évora" },
  { dico: "1609", name: "Viana do Castelo", district: "Viana do Castelo" },
  { dico: "0214", name: "Vidigueira", district: "Beja" },
  { dico: "0311", name: "Vieira do Minho", district: "Braga" },
  { dico: "0510", name: "Vila de Rei", district: "Castelo Branco" },
  { dico: "0815", name: "Vila do Bispo", district: "Faro" },
  { dico: "1316", name: "Vila do Conde", district: "Porto" },
  { dico: "0410", name: "Vila Flor", district: "Bragança" },
  { dico: "1114", name: "Vila Franca de Xira", district: "Lisboa" },
  { dico: "1420", name: "Vila Nova da Barquinha", district: "Santarém" },
  { dico: "1610", name: "Vila Nova de Cerveira", district: "Viana do Castelo" },
  { dico: "0312", name: "Vila Nova de Famalicão", district: "Braga" },
  { dico: "0914", name: "Vila Nova de Foz Côa", district: "Guarda" },
  { dico: "1317", name: "Vila Nova de Gaia", district: "Porto" },
  { dico: "1822", name: "Vila Nova de Paiva", district: "Viseu" },
  { dico: "0617", name: "Vila Nova de Poiares", district: "Coimbra" },
  { dico: "1713", name: "Vila Pouca de Aguiar", district: "Vila Real" },
  { dico: "1714", name: "Vila Real", district: "Vila Real" },
  { dico: "0816", name: "Vila Real de Santo António", district: "Faro" },
  { dico: "0511", name: "Vila Velha de Ródão", district: "Castelo Branco" },
  { dico: "0313", name: "Vila Verde", district: "Braga" },
  { dico: "0714", name: "Vila Viçosa", district: "Évora" },
  { dico: "0411", name: "Vimioso", district: "Bragança" },
  { dico: "0412", name: "Vinhais", district: "Bragança" },
  { dico: "1823", name: "Viseu", district: "Viseu" },
  { dico: "0314", name: "Vizela", district: "Braga" },
  { dico: "1824", name: "Vouzela", district: "Viseu" },
]

/** Strip accents + lowercase for accent-insensitive search. */
function fold(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim()
}

/**
 * Concelhos whose name or district matches every whitespace-separated term in
 * the query (accent-insensitive), name-sorted, capped at `limit`. Empty query
 * returns the first `limit` concelhos.
 */
export function searchConcelhos(query: string, limit = 8): ConcelhoEntry[] {
  const terms = fold(query).split(/\s+/).filter(Boolean)
  if (terms.length === 0) return CONCELHOS.slice(0, limit)
  const result: ConcelhoEntry[] = []
  for (const c of CONCELHOS) {
    const hay = fold(c.name + " " + c.district)
    if (terms.every((t) => hay.includes(t))) {
      result.push(c)
      if (result.length >= limit) break
    }
  }
  return result
}

/** Exact DICO lookup, or null. */
export function concelhoByDico(dico: string): ConcelhoEntry | null {
  return CONCELHOS.find((c) => c.dico === dico) ?? null
}

const BY_FOLDED_NAME = new Map<string, ConcelhoEntry>(
  CONCELHOS.map((c) => [fold(c.name), c]),
)

/**
 * Accent-insensitive lookup by concelho name (incidents carry the name, not a
 * DICO). Returns null when the name isn't in the mainland concelho set (islands,
 * spelling drift). Used to link an incident's concelho to its profile page.
 */
export function concelhoByName(name: string): ConcelhoEntry | null {
  return BY_FOLDED_NAME.get(fold(name)) ?? null
}
