/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as OcorrenciasRouteImport } from './routes/ocorrencias'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ApiRouteImport } from './routes/api'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConcelhoDicoRouteImport } from './routes/concelho.$dico'
import { Route as ApiWeatherTilesRouteImport } from './routes/api/weather-tiles'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const OcorrenciasRoute = OcorrenciasRouteImport.update({
  id: '/ocorrencias',
  path: '/ocorrencias',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcelhoDicoRoute = ConcelhoDicoRouteImport.update({
  id: '/concelho/$dico',
  path: '/concelho/$dico',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherTilesRoute = ApiWeatherTilesRouteImport.update({
  id: '/weather-tiles',
  path: '/weather-tiles',
  getParentRoute: () => ApiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/conta': typeof ContaRoute
  '/creditos': typeof CreditosRoute
  '/estatisticas': typeof EstatisticasRoute
  '/ocorrencias': typeof OcorrenciasRoute
  '/sobre': typeof SobreRoute
  '/api/weather-tiles': typeof ApiWeatherTilesRoute
  '/concelho/$dico': typeof ConcelhoDicoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/conta': typeof ContaRoute
  '/creditos': typeof CreditosRoute
  '/estatisticas': typeof EstatisticasRoute
  '/ocorrencias': typeof OcorrenciasRoute
  '/sobre': typeof SobreRoute
  '/api/weather-tiles': typeof ApiWeatherTilesRoute
  '/concelho/$dico': typeof ConcelhoDicoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/conta': typeof ContaRoute
  '/creditos': typeof CreditosRoute
  '/estatisticas': typeof EstatisticasRoute
  '/ocorrencias': typeof OcorrenciasRoute
  '/sobre': typeof SobreRoute
  '/api/weather-tiles': typeof ApiWeatherTilesRoute
  '/concelho/$dico': typeof ConcelhoDicoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/conta'
    | '/creditos'
    | '/estatisticas'
    | '/ocorrencias'
    | '/sobre'
    | '/api/weather-tiles'
    | '/concelho/$dico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/conta'
    | '/creditos'
    | '/estatisticas'
    | '/ocorrencias'
    | '/sobre'
    | '/api/weather-tiles'
    | '/concelho/$dico'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/conta'
    | '/creditos'
    | '/estatisticas'
    | '/ocorrencias'
    | '/sobre'
    | '/api/weather-tiles'
    | '/concelho/$dico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRouteWithChildren
  ContaRoute: typeof ContaRoute
  CreditosRoute: typeof CreditosRoute
  EstatisticasRoute: typeof EstatisticasRoute
  OcorrenciasRoute: typeof OcorrenciasRoute
  SobreRoute: typeof SobreRoute
  ConcelhoDicoRoute: typeof ConcelhoDicoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocorrencias': {
      id: '/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/ocorrencias'
      preLoaderRoute: typeof OcorrenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concelho/$dico': {
      id: '/concelho/$dico'
      path: '/concelho/$dico'
      fullPath: '/concelho/$dico'
      preLoaderRoute: typeof ConcelhoDicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather-tiles': {
      id: '/api/weather-tiles'
      path: '/weather-tiles'
      fullPath: '/api/weather-tiles'
      preLoaderRoute: typeof ApiWeatherTilesRouteImport
      parentRoute: typeof ApiRoute
    }
  }
}

interface ApiRouteChildren {
  ApiWeatherTilesRoute: typeof ApiWeatherTilesRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiWeatherTilesRoute: ApiWeatherTilesRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRouteWithChildren,
  ContaRoute: ContaRoute,
  CreditosRoute: CreditosRoute,
  EstatisticasRoute: EstatisticasRoute,
  OcorrenciasRoute: OcorrenciasRoute,
  SobreRoute: SobreRoute,
  ConcelhoDicoRoute: ConcelhoDicoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
